[package]
name = "beditor"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
iced = { version = "0.12", features = ["debug", "image", "advanced"] }

bedrock-rs = { path = "../bedrock-rs" }
